id: IE422772D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:01:52+00:00'
last_modified: '2022-06-07T15:23:01.696676+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105804
  title: རུས་སྦྱོར་གཡུ་ཐོག་དགྱེས་པའི་མཆོད་སྤྲིན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    18AE:
      image_group_id: I1PD105806
      title: ''
      total_pages: 222
      order: 1
      base_file: 18AE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
